export type CasperBackendMode = 'shared' | 'dedicated';

export type CasperSiteProfile = {
  slug: string;
  apiSlug: string;
  locationSlug: string;
  name: string;
  format: string;
  tagline: string;
  description: string;
  accent: string;
  accentBright: string;
  secondary: string;
  logo: string;
  heroImage: string;
  backend: CasperBackendMode;
  edgeFunction?: string;
  serviceMode: 'service' | 'catering';
  clubMode: 'club' | 'vip';
  serviceLabel: string;
  clubLabel: string;
  itemNoun: string;
};

export const CASPER_SECTIONS = [
  'menu',
  'order',
  'catering',
  'locations',
  'about',
  'rewards',
  'contact',
] as const;

export type CasperSection = (typeof CASPER_SECTIONS)[number];

export const casperSiteProfiles: Record<string, CasperSiteProfile> = {
  'angel-wings': {
    slug: 'angel-wings',
    apiSlug: 'angel-wings',
    locationSlug: 'angel-wings',
    name: 'Angel Wings',
    format: 'Wings · Shrimp · Fries',
    tagline: 'Heaven-sent heat. Atlanta attitude.',
    description: 'Sauced-to-order wings, shrimp, fries, and late-night baskets engineered for craveability, delivery speed, and repeat orders.',
    accent: '#C85A1A',
    accentBright: '#F08A42',
    secondary: '#D89A2B',
    logo: '/images/logo-angel-wings.png',
    heroImage: '/images/angel-wings-hero.jpg',
    backend: 'dedicated',
    edgeFunction: 'angel-wings-intake',
    serviceMode: 'catering',
    clubMode: 'vip',
    serviceLabel: 'Catering',
    clubLabel: 'VIP',
    itemNoun: 'basket',
  },
  'tha-morning-after': {
    slug: 'tha-morning-after',
    apiSlug: 'the-morning-after',
    locationSlug: 'morning-after',
    name: 'Tha Morning After',
    format: 'Breakfast · Brunch · Recovery',
    tagline: 'Recovery served hot.',
    description: 'Breakfast sandwiches, brunch bowls, sweet stacks, and late-night recovery food built to travel and hit when the night is over.',
    accent: '#F19B43',
    accentBright: '#FFD075',
    secondary: '#E7637C',
    logo: '/images/logo-the-morning-after.png',
    heroImage: '/images/portal-the-morning-after.jpeg',
    backend: 'shared',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Brunch Catering',
    clubLabel: 'Recovery List',
    itemNoun: 'recovery meal',
  },
  'patty-daddy': {
    slug: 'patty-daddy',
    apiSlug: 'patty-daddy',
    locationSlug: 'patty-daddy',
    name: 'Patty Daddy',
    format: 'Smash Burgers · Fries · Shakes',
    tagline: 'Built like a boss. Smashed like it matters.',
    description: 'Hard-seared smash burgers, crisp fries, layered sauces, and delivery-built stacks with no weak edges.',
    accent: '#E24B32',
    accentBright: '#FF7759',
    secondary: '#F6BD32',
    logo: '/images/logo-patty-daddy.png',
    heroImage: '/images/portal-patty-daddy.jpeg',
    backend: 'shared',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Group Orders',
    clubLabel: 'Daddy List',
    itemNoun: 'burger',
  },
  'espresso-co': {
    slug: 'espresso-co',
    apiSlug: 'espresso-co',
    locationSlug: 'espresso-co',
    name: 'Espresso Co.',
    format: 'Espresso · Coffee · Mobile Bar',
    tagline: 'The science of the perfect cup.',
    description: 'Modern coffee culture with lab-level precision: espresso, pour-over, cold brew, signatures, office programs, and event coffee service.',
    accent: '#8A6A3A',
    accentBright: '#B7965F',
    secondary: '#D89A2B',
    logo: '/images/logo-espresso-co.png',
    heroImage: '/images/espresso-machine.jpg',
    backend: 'dedicated',
    edgeFunction: 'espresso-co-intake',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Coffee Service',
    clubLabel: 'Coffee Club',
    itemNoun: 'drink',
  },
  'mojo-juice': {
    slug: 'mojo-juice',
    apiSlug: 'mojo-juice',
    locationSlug: 'mojo-juice',
    name: 'Mojo Juice',
    format: 'Juices · Smoothies · Wellness',
    tagline: 'Put the energy back.',
    description: 'Cold-pressed juices, smoothies, wellness shots, bowls, and office packs built around fresh ingredients and useful function.',
    accent: '#91C83E',
    accentBright: '#C4F06D',
    secondary: '#F5A43C',
    logo: '/images/logo-mojo-juice.png',
    heroImage: '/images/portal-mojo-juice.jpeg',
    backend: 'shared',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Wellness Drops',
    clubLabel: 'Mojo List',
    itemNoun: 'drink',
  },
  'mr-oyster': {
    slug: 'mr-oyster',
    apiSlug: 'mr-oyster',
    locationSlug: 'mr-oyster',
    name: 'Mr. Oyster',
    format: 'Oysters · Seafood · Raw Bar',
    tagline: 'Pearl of the sea.',
    description: 'A sharp, transport-aware seafood concept built around oysters, shellfish, premium pairings, and event-ready raw bar service.',
    accent: '#4B93A8',
    accentBright: '#7BC2D4',
    secondary: '#D5C7A5',
    logo: '/images/logo-mr-oyster.png',
    heroImage: '/images/portal-mr-oyster.jpeg',
    backend: 'shared',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Raw Bar Service',
    clubLabel: 'Pearl List',
    itemNoun: 'seafood item',
  },
  'sweet-tooth': {
    slug: 'sweet-tooth',
    apiSlug: 'sweet-tooth',
    locationSlug: 'sweet-tooth',
    name: 'Sweet Tooth',
    format: 'Desserts · Shakes · Celebration',
    tagline: 'Give in to the good part.',
    description: 'Warm cookies, brownies, cheesecake jars, loaded shakes, celebration trays, and custom dessert programs made to arrive like a moment.',
    accent: '#E45C9D',
    accentBright: '#FF8FC3',
    secondary: '#8F63D8',
    logo: '/images/logo-sweet-tooth.png',
    heroImage: '/images/portal-sweet-tooth.jpeg',
    backend: 'shared',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Celebrations',
    clubLabel: 'Craving List',
    itemNoun: 'dessert',
  },
  'taco-yaki': {
    slug: 'taco-yaki',
    apiSlug: 'taco-yaki',
    locationSlug: 'taco-yaki',
    name: 'Taco Yaki',
    format: 'Tacos · Hibachi · Fire',
    tagline: 'Fire meets flavor.',
    description: 'Taco energy meets hibachi technique with grilled proteins, rice builds, sauces, and live-grill catering engineered for speed.',
    accent: '#E84A2A',
    accentBright: '#FF7652',
    secondary: '#F0B83F',
    logo: '/images/logo-taco-yaki.png',
    heroImage: '/images/portal-taco-yaki.jpeg',
    backend: 'dedicated',
    edgeFunction: 'taco-yaki-intake',
    serviceMode: 'catering',
    clubMode: 'club',
    serviceLabel: 'Live Grill Catering',
    clubLabel: 'Fire Club',
    itemNoun: 'build',
  },
  'tossd': {
    slug: 'tossd',
    apiSlug: 'tossd',
    locationSlug: 'tossd',
    name: 'Toss’d',
    format: 'Salads · Wraps · Grain Bowls',
    tagline: 'Fresh enough to crave.',
    description: 'Chopped salads, grain bowls, wraps, protein boxes, and office programs that make clean eating feel like an actual meal.',
    accent: '#64A94F',
    accentBright: '#9AD86F',
    secondary: '#E7C94F',
    logo: '/images/logo-tossd.png',
    heroImage: '/images/portal-tossd.jpeg',
    backend: 'shared',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Office & Wellness',
    clubLabel: 'Fresh List',
    itemNoun: 'fresh build',
  },
  'pasta-bish': {
    slug: 'pasta-bish',
    apiSlug: 'pasta-bish',
    locationSlug: 'pasta-bish',
    name: 'Pasta Bish',
    format: 'Pasta · Bowls · Italian Energy',
    tagline: 'Fresh pasta. Bold flavor.',
    description: 'Saucy pasta builds, proteins, noodles, and late-night Italian comfort with a customization system made for delivery and events.',
    accent: '#C64568',
    accentBright: '#F06F91',
    secondary: '#F0B65D',
    logo: '/images/logo-pasta-bish.png',
    heroImage: '/images/portal-pasta-bish.jpeg',
    backend: 'dedicated',
    edgeFunction: 'pasta-bish-intake',
    serviceMode: 'catering',
    clubMode: 'club',
    serviceLabel: 'Pasta Catering',
    clubLabel: 'Pasta Bish Club',
    itemNoun: 'pasta',
  },
  'peace-pizza': {
    slug: 'peace-pizza',
    apiSlug: 'peace-pizza',
    locationSlug: 'peace-pizza',
    name: 'Peace Pizza',
    format: 'Pizza · Slices · Good Energy',
    tagline: 'Spread the slice.',
    description: 'A culture-first pizza concept built around crisp pies, creative toppings, group orders, and an easygoing brand with serious kitchen discipline.',
    accent: '#5FA75F',
    accentBright: '#8BD182',
    secondary: '#E4A64C',
    logo: '/images/logo-peace-pizza.png',
    heroImage: '/images/portal-peace-pizza.jpeg',
    backend: 'shared',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Group Pizza',
    clubLabel: 'Peace List',
    itemNoun: 'pizza',
  },
  'american-dragon': {
    slug: 'american-dragon',
    apiSlug: 'american-dragon',
    locationSlug: 'american-dragon',
    name: 'American Dragon',
    format: 'American Chinese · Luxury Takeout',
    tagline: 'Takeout with a sharper edge.',
    description: 'American-Chinese classics rebuilt as premium takeout: wok-fired flavor, crisp texture, strong packaging, and an elevated late-night lane.',
    accent: '#B83A32',
    accentBright: '#E76556',
    secondary: '#D3A943',
    logo: '/images/logo-american-dragon.png',
    heroImage: '/images/portal-american-dragon.jpeg',
    backend: 'shared',
    serviceMode: 'service',
    clubMode: 'club',
    serviceLabel: 'Group Takeout',
    clubLabel: 'Dragon List',
    itemNoun: 'dish',
  },
};

export const casperBrandSlugs = Object.keys(casperSiteProfiles);

export function getCasperSiteProfile(slug: string) {
  return casperSiteProfiles[slug] || null;
}

export function isCasperSection(value: string): value is CasperSection {
  return CASPER_SECTIONS.includes(value as CasperSection);
}
