export type ServiceOption = {
  value: string;
  label: string;
};

export type CasperCommerceBrand = {
  slug: string;
  name: string;
  logo: string;
  heroImage: string;
  accent: string;
  accentBright: string;
  accentDark: string;
  secondary: string;
  eyebrow: string;
  format: string;
  heroLead: string;
  heroAccent: string;
  heroTail: string;
  heroCopy: string;
  orderCta: string;
  serviceCta: string;
  signatureEyebrow: string;
  signatureHeading: string;
  standardEyebrow: string;
  standardHeading: string;
  standardAccent: string;
  standardCopy: string;
  standards: [string, string, string];
  menuEyebrow: string;
  menuHeading: string;
  systemEyebrow: string;
  systemHeading: string;
  systemCopy: string;
  systemSteps: Array<{ title: string; detail: string }>;
  serviceEyebrow: string;
  serviceHeading: string;
  serviceCopy: string;
  serviceOptions: ServiceOption[];
  serviceTags: string[];
  clubName: string;
  clubHeading: string;
  clubCopy: string;
  favoriteLabel: string;
  favoritePlaceholder: string;
  itemNoun: string;
  legalNote?: string;
};

export const remainingCasperBrands: Record<string, CasperCommerceBrand> = {
  "patty-daddy": {
    slug: "patty-daddy",
    name: "Patty Daddy",
    logo: "/images/logo-patty-daddy.png",
    heroImage: "/images/portal-patty-daddy.jpeg",
    accent: "#e24b32",
    accentBright: "#ff7759",
    accentDark: "#7d2018",
    secondary: "#f6bd32",
    eyebrow: "A Casper Group Brand · Smash Burger House",
    format: "Smash burgers · Fries · Shakes",
    heroLead: "Built like a",
    heroAccent: "boss.",
    heroTail: "Smashed like it matters.",
    heroCopy: "Hard sear, crisp edges, melted cheese, proper sauce, and enough structure to survive delivery without losing the point.",
    orderCta: "Build a Burger Order",
    serviceCta: "Feed the Function",
    signatureEyebrow: "Daddy-approved",
    signatureHeading: "The burgers that run the room.",
    standardEyebrow: "The smash standard",
    standardHeading: "Edges crisp. Center juicy.",
    standardAccent: "No weak burgers.",
    standardCopy: "Patty Daddy is disciplined indulgence: hot griddle contact, exact patty weight, controlled sauce, toasted buns, and packaging that protects the crust.",
    standards: ["Smash on contact", "Stack with balance", "Pack for the ride"],
    menuEyebrow: "The launch menu",
    menuHeading: "Choose your Daddy behavior.",
    systemEyebrow: "The build system",
    systemHeading: "Patty. Cheese. Finish. No confusion.",
    systemCopy: "The menu stays fast because every choice has a lane. Pick the build, control the stack, choose the finish, and let the griddle do the rest.",
    systemSteps: [
      { title: "Choose the build", detail: "Double smash · Triple · Chicken · Plant" },
      { title: "Set the cheese", detail: "American · Pepper Jack · Swiss · None" },
      { title: "Control the sauce", detail: "Daddy · Spicy Daddy · Dry" },
      { title: "Make it a move", detail: "Fries · Rings · Shake · Family pack" },
    ],
    serviceEyebrow: "Catering & group orders",
    serviceHeading: "Bring burgers people actually remember.",
    serviceCopy: "Office lunches, game nights, private parties, production sets, festivals, and bulk pickup built around a clean service plan.",
    serviceOptions: [
      { value: "group_order", label: "Group order" },
      { value: "catering", label: "Catering" },
      { value: "food_truck", label: "Food truck" },
      { value: "custom", label: "Custom program" },
    ],
    serviceTags: ["Drop-off", "Pickup", "Boxed meals", "Food truck"],
    clubName: "The Daddy List",
    clubHeading: "First access. Bigger appetite.",
    clubCopy: "Join for burger drops, limited stacks, late-night windows, birthday offers, and first access to new locations.",
    favoriteLabel: "Favorite burger build",
    favoritePlaceholder: "Double smash, spicy sauce, no onions…",
    itemNoun: "burger",
  },
  "the-morning-after": {
    slug: "the-morning-after",
    name: "The Morning After",
    logo: "/images/logo-the-morning-after.png",
    heroImage: "/images/portal-the-morning-after.jpeg",
    accent: "#f19b43",
    accentBright: "#ffd075",
    accentDark: "#8a4922",
    secondary: "#e7637c",
    eyebrow: "A Casper Group Brand · Breakfast & Recovery",
    format: "Breakfast · Brunch · Recovery",
    heroLead: "Recovery",
    heroAccent: "served hot.",
    heroTail: "No explanations required.",
    heroCopy: "Breakfast sandwiches, brunch bowls, sweet stacks, and the kind of food that makes last night feel like a better decision.",
    orderCta: "Build a Recovery Order",
    serviceCta: "Book Brunch Service",
    signatureEyebrow: "The recovery menu",
    signatureHeading: "Breakfast built for real mornings.",
    standardEyebrow: "The next-day standard",
    standardHeading: "Hot, fast, generous.",
    standardAccent: "Back to life.",
    standardCopy: "The Morning After is engineered for comfort without sloppiness: hot eggs, crisp potatoes, balanced sandwiches, transport-safe packaging, and brunch service that can scale.",
    standards: ["Eggs stay tender", "Potatoes stay crisp", "Sauce stays controlled"],
    menuEyebrow: "The recovery menu",
    menuHeading: "Pick what the morning requires.",
    systemEyebrow: "The recovery system",
    systemHeading: "Savory, sweet, or full reset.",
    systemCopy: "Choose a sandwich, wrap, bowl, plate, or sweet stack. Every build is designed to travel, reheat, and still feel like brunch—not leftovers.",
    systemSteps: [
      { title: "Choose the format", detail: "Sandwich · Wrap · Bowl · Plate" },
      { title: "Pick the protein", detail: "Bacon · Sausage · Steak · Chicken" },
      { title: "Add the sweet", detail: "French toast · Pancakes · Fruit" },
      { title: "Make it group-ready", detail: "Boxes · Platters · Office brunch" },
    ],
    serviceEyebrow: "Brunch catering",
    serviceHeading: "Save the whole group the next morning.",
    serviceCopy: "Birthday brunches, office recovery, wedding mornings, production sets, hotel drops, and private breakfast service.",
    serviceOptions: [
      { value: "brunch_catering", label: "Brunch catering" },
      { value: "breakfast_drop", label: "Breakfast drop" },
      { value: "boxed_meals", label: "Boxed meals" },
      { value: "custom", label: "Custom program" },
    ],
    serviceTags: ["Breakfast drop", "Brunch buffet", "Boxed meals", "Private service"],
    clubName: "The Recovery List",
    clubHeading: "Wake up before everybody else.",
    clubCopy: "Join for brunch windows, new recovery builds, birthday offers, event drops, and first access to opening dates.",
    favoriteLabel: "Favorite recovery meal",
    favoritePlaceholder: "Chicken biscuit, brunch bowl, French toast…",
    itemNoun: "breakfast item",
  },
  "tossd": {
    slug: "tossd",
    name: "Toss’d",
    logo: "/images/logo-tossd.png",
    heroImage: "/images/portal-tossd.jpeg",
    accent: "#64a94f",
    accentBright: "#9ad86f",
    accentDark: "#315d29",
    secondary: "#e7c94f",
    eyebrow: "A Casper Group Brand · Salad & Bowl Kitchen",
    format: "Salads · Wraps · Grain Bowls",
    heroLead: "Fresh enough to",
    heroAccent: "crave.",
    heroTail: "Built to keep you moving.",
    heroCopy: "Chopped salads, grain bowls, wraps, protein boxes, and office programs that make eating clean feel like a real meal.",
    orderCta: "Build a Fresh Order",
    serviceCta: "Plan Office Lunch",
    signatureEyebrow: "Signature tosses",
    signatureHeading: "Clean food with actual personality.",
    standardEyebrow: "The fresh standard",
    standardHeading: "Cold stays cold. Crunch stays loud.",
    standardAccent: "Nothing tired.",
    standardCopy: "Toss’d is built around ingredient rotation, prep discipline, portion accuracy, dressing control, and packaging that protects texture through delivery.",
    standards: ["Prep daily", "Dress with control", "Protect the crunch"],
    menuEyebrow: "The launch menu",
    menuHeading: "Choose the way you want to feel.",
    systemEyebrow: "The Toss’d system",
    systemHeading: "Base. Protein. Color. Crunch.",
    systemCopy: "The build stays flexible and operationally clean. Choose the foundation, add protein, layer vegetables, finish with texture, and control the dressing.",
    systemSteps: [
      { title: "Choose the base", detail: "Romaine · Kale · Greens · Quinoa" },
      { title: "Add the protein", detail: "Chicken · Steak · Shrimp · Falafel" },
      { title: "Layer the color", detail: "Vegetables · Fruit · Cheese · Herbs" },
      { title: "Finish it", detail: "Crunch · Dressing · Wrap or bowl" },
    ],
    serviceEyebrow: "Office & wellness catering",
    serviceHeading: "Lunch that keeps the room productive.",
    serviceCopy: "Recurring office lunch, meetings, wellness events, production sets, boxed meals, and large-format salad service.",
    serviceOptions: [
      { value: "office_lunch", label: "Office lunch" },
      { value: "boxed_meals", label: "Boxed meals" },
      { value: "wellness_event", label: "Wellness event" },
      { value: "subscription", label: "Recurring program" },
    ],
    serviceTags: ["Office lunch", "Boxed meals", "Buffet bowls", "Recurring service"],
    clubName: "The Fresh List",
    clubHeading: "Your lunch should know the assignment.",
    clubCopy: "Join for seasonal bowls, member offers, office ordering windows, wellness drops, and first access to new locations.",
    favoriteLabel: "Favorite salad or bowl",
    favoritePlaceholder: "ATL Chopped, Green Goddess, custom build…",
    itemNoun: "fresh build",
  },
  "sweet-tooth": {
    slug: "sweet-tooth",
    name: "Sweet Tooth",
    logo: "/images/logo-sweet-tooth.png",
    heroImage: "/images/portal-sweet-tooth.jpeg",
    accent: "#e45c9d",
    accentBright: "#ff8fc3",
    accentDark: "#7e2755",
    secondary: "#8f63d8",
    eyebrow: "A Casper Group Brand · Dessert Bar",
    format: "Desserts · Shakes · Celebration",
    heroLead: "Give in to the",
    heroAccent: "good part.",
    heroTail: "Dessert without restraint.",
    heroCopy: "Warm cookies, brownies, cheesecake jars, loaded shakes, celebration trays, and custom cake requests built for late nights and big moments.",
    orderCta: "Build a Dessert Order",
    serviceCta: "Plan a Celebration",
    signatureEyebrow: "Signature cravings",
    signatureHeading: "The desserts worth breaking routine for.",
    standardEyebrow: "The dessert standard",
    standardHeading: "Warm, layered, excessive.",
    standardAccent: "Still balanced.",
    standardCopy: "Sweet Tooth controls temperature, texture, sauce, and packaging so a dessert arrives layered—not collapsed—and a celebration order looks intentional.",
    standards: ["Bake for texture", "Layer with purpose", "Pack like a gift"],
    menuEyebrow: "The craving menu",
    menuHeading: "Choose the level of temptation.",
    systemEyebrow: "The dessert system",
    systemHeading: "Warm base. Cold finish. Loud topping.",
    systemCopy: "Pick the foundation, add the cream or ice cream, choose the sauce, then finish with texture. The result should feel indulgent, not random.",
    systemSteps: [
      { title: "Choose the base", detail: "Cookie · Brownie · Cake · Waffle" },
      { title: "Add the cold", detail: "Ice cream · Cheesecake cream · Pudding" },
      { title: "Choose the sauce", detail: "Chocolate · Caramel · Fruit · Cookie butter" },
      { title: "Finish the moment", detail: "Crumbs · Candy · Fruit · Celebration message" },
    ],
    serviceEyebrow: "Celebrations & dessert catering",
    serviceHeading: "Make the dessert table the main event.",
    serviceCopy: "Birthdays, office celebrations, weddings, launches, gifting, custom cakes, dessert trays, and branded sweet programs.",
    serviceOptions: [
      { value: "dessert_catering", label: "Dessert catering" },
      { value: "custom_cake", label: "Custom cake" },
      { value: "corporate_gifting", label: "Corporate gifting" },
      { value: "dessert_bar", label: "Staffed dessert bar" },
    ],
    serviceTags: ["Dessert trays", "Custom cakes", "Gifting", "Staffed bar"],
    clubName: "The Craving List",
    clubHeading: "Hear about the drop before it disappears.",
    clubCopy: "Join for dessert drops, birthday offers, limited flavors, celebration windows, and first access to new locations.",
    favoriteLabel: "Favorite dessert",
    favoritePlaceholder: "Brownie overload, cheesecake jar, loaded shake…",
    itemNoun: "dessert",
  },
  "mojo-juice": {
    slug: "mojo-juice",
    name: "Mojo Juice",
    logo: "/images/logo-mojo-juice.png",
    heroImage: "/images/portal-mojo-juice.jpeg",
    accent: "#91c83e",
    accentBright: "#c4f06d",
    accentDark: "#496f20",
    secondary: "#f5a43c",
    eyebrow: "A Casper Group Brand · Juice & Wellness Bar",
    format: "Juices · Smoothies · Wellness",
    heroLead: "Put the",
    heroAccent: "energy back.",
    heroTail: "Drink with purpose.",
    heroCopy: "Cold-pressed juices, smoothies, wellness shots, bowls, and office packs built around real ingredients and useful function.",
    orderCta: "Build a Mojo Order",
    serviceCta: "Plan a Wellness Drop",
    signatureEyebrow: "Functional favorites",
    signatureHeading: "Flavor first. Function built in.",
    standardEyebrow: "The juice standard",
    standardHeading: "Fresh ingredients. Clear purpose.",
    standardAccent: "No fake wellness theater.",
    standardCopy: "Mojo Juice prioritizes ingredient quality, cold-chain discipline, exact recipes, useful add-ins, and packaging that keeps the product bright and safe.",
    standards: ["Prep fresh", "Measure the function", "Protect the cold chain"],
    menuEyebrow: "The wellness menu",
    menuHeading: "Choose what your day needs.",
    systemEyebrow: "The Mojo system",
    systemHeading: "Hydrate. Fuel. Recover. Reset.",
    systemCopy: "Choose the goal, pick the format, add the functional boost, and keep the ingredient list understandable.",
    systemSteps: [
      { title: "Choose the goal", detail: "Energy · Immunity · Recovery · Glow" },
      { title: "Pick the format", detail: "Juice · Smoothie · Shot · Bowl" },
      { title: "Add the boost", detail: "Protein · Greens · Collagen · Ginger" },
      { title: "Build the routine", detail: "Single order · Pack · Office program" },
    ],
    serviceEyebrow: "Wellness programs & events",
    serviceHeading: "Give the team something better than another coffee run.",
    serviceCopy: "Office juice programs, wellness activations, fitness events, production sets, branded bottles, and group packs.",
    serviceOptions: [
      { value: "office_program", label: "Office program" },
      { value: "wellness_event", label: "Wellness event" },
      { value: "juice_pack", label: "Juice pack" },
      { value: "white_label", label: "Branded or white-label inquiry" },
    ],
    serviceTags: ["Office packs", "Wellness events", "Fitness activations", "Branded service"],
    clubName: "The Mojo List",
    clubHeading: "Keep your next reset close.",
    clubCopy: "Join for seasonal blends, wellness packs, member offers, event windows, and first access to new locations.",
    favoriteLabel: "Favorite juice or goal",
    favoritePlaceholder: "Green juice, recovery smoothie, immunity…",
    itemNoun: "juice or smoothie",
    legalNote: "Menu language describes general product positioning and is not medical advice.",
  },
  "mr-oyster": {
    slug: "mr-oyster",
    name: "Mr. Oyster",
    logo: "/images/logo-mr-oyster.png",
    heroImage: "/images/portal-mr-oyster.jpeg",
    accent: "#5aa7a8",
    accentBright: "#8bd5d2",
    accentDark: "#285c61",
    secondary: "#d5b777",
    eyebrow: "A Casper Group Brand · Oyster & Seafood Bar",
    format: "Oysters · Seafood · Raw Bar",
    heroLead: "The coast came",
    heroAccent: "outside.",
    heroTail: "Fresh, fired, and fully dressed.",
    heroCopy: "Raw oysters, chargrilled favorites, seafood baskets, boils, rolls, and event-ready raw-bar service with real hospitality behind it.",
    orderCta: "Build a Seafood Order",
    serviceCta: "Book the Raw Bar",
    signatureEyebrow: "Raw, grilled, loaded",
    signatureHeading: "Seafood with a point of view.",
    standardEyebrow: "The seafood standard",
    standardHeading: "Cold chain exact. Fire controlled.",
    standardAccent: "No shortcuts around freshness.",
    standardCopy: "Mr. Oyster treats sourcing, temperature, handling, cook times, shell presentation, and delivery windows as non-negotiable operating controls.",
    standards: ["Source responsibly", "Hold temperature", "Fire to order"],
    menuEyebrow: "The seafood menu",
    menuHeading: "Choose raw, fired, fried, or boiled.",
    systemEyebrow: "The Mr. Oyster system",
    systemHeading: "Cold bar precision. Hot line energy.",
    systemCopy: "The experience moves from chilled oysters to chargrilled shells, seafood baskets, boils, and party platters without losing control of quality.",
    systemSteps: [
      { title: "Choose the coast", detail: "Raw oysters · Shrimp · Crab · Lobster" },
      { title: "Pick the treatment", detail: "Chilled · Chargrilled · Fried · Boiled" },
      { title: "Set the seasoning", detail: "Classic · Garlic butter · Cajun · House blend" },
      { title: "Scale the service", detail: "Basket · Platter · Raw bar · Event" },
    ],
    serviceEyebrow: "Raw bars & seafood catering",
    serviceHeading: "Make the seafood station the room’s destination.",
    serviceCopy: "Private events, weddings, corporate functions, seafood drops, staffed raw bars, boils, and festival service.",
    serviceOptions: [
      { value: "raw_bar", label: "Staffed raw bar" },
      { value: "seafood_catering", label: "Seafood catering" },
      { value: "seafood_boiling", label: "Seafood boil" },
      { value: "festival", label: "Festival or mobile service" },
    ],
    serviceTags: ["Raw bar", "Drop-off", "Seafood boil", "Mobile service"],
    clubName: "The Oyster List",
    clubHeading: "Know when the next catch lands.",
    clubCopy: "Join for oyster drops, raw-bar events, seafood specials, birthday offers, and first access to new service windows.",
    favoriteLabel: "Favorite seafood order",
    favoritePlaceholder: "Raw dozen, chargrilled, seafood boil…",
    itemNoun: "seafood item",
    legalNote: "Consuming raw or undercooked seafood may increase the risk of foodborne illness.",
  },
  "peace-pizza": {
    slug: "peace-pizza",
    name: "Peace Pizza",
    logo: "/images/logo-peace-pizza.png",
    heroImage: "/images/portal-peace-pizza.jpeg",
    accent: "#d7483d",
    accentBright: "#ff776a",
    accentDark: "#7c231f",
    secondary: "#e6c655",
    eyebrow: "A Casper Group Brand · Pizza Kitchen",
    format: "Pizza · Wings · Good Energy",
    heroLead: "Make pizza,",
    heroAccent: "not problems.",
    heroTail: "Everybody gets a piece.",
    heroCopy: "Whole pies, slices, wings, salads, garlic knots, and party packs built for neighborhoods, late nights, and rooms full of people.",
    orderCta: "Build a Pizza Order",
    serviceCta: "Plan a Pizza Party",
    signatureEyebrow: "Pies with purpose",
    signatureHeading: "The pizzas that keep the peace.",
    standardEyebrow: "The pizza standard",
    standardHeading: "Crisp base. Proper melt.",
    standardAccent: "No sad delivery pie.",
    standardCopy: "Peace Pizza controls fermentation, bake, topping weight, slice structure, venting, and delivery timing so the pie arrives like pizza—not steam-softened bread.",
    standards: ["Ferment for flavor", "Top with balance", "Vent the box"],
    menuEyebrow: "The peace menu",
    menuHeading: "Choose the pie everybody can agree on.",
    systemEyebrow: "The pizza system",
    systemHeading: "Size. Crust. Toppings. Peace restored.",
    systemCopy: "Start with the pie, choose the size and crust, control the toppings, add wings or knots, and scale up to a full party pack.",
    systemSteps: [
      { title: "Choose the pie", detail: "Classic · Pepperoni · White · Garden" },
      { title: "Set the size", detail: "12-inch · 16-inch · Party order" },
      { title: "Add the sides", detail: "Wings · Knots · Salad" },
      { title: "Feed the room", detail: "Whole pies · Packs · Catering" },
    ],
    serviceEyebrow: "Parties & group orders",
    serviceHeading: "The easiest way to feed everybody well.",
    serviceCopy: "Birthdays, offices, schools, team meals, festivals, private events, late-night drops, and recurring group orders.",
    serviceOptions: [
      { value: "pizza_party", label: "Pizza party" },
      { value: "office_order", label: "Office or team order" },
      { value: "school_program", label: "School or community program" },
      { value: "festival", label: "Festival or mobile service" },
    ],
    serviceTags: ["Party packs", "Office orders", "Community events", "Mobile service"],
    clubName: "The Peace List",
    clubHeading: "Good news travels by the slice.",
    clubCopy: "Join for new pies, neighborhood drops, member offers, event windows, and first access to new locations.",
    favoriteLabel: "Favorite pizza",
    favoritePlaceholder: "Pepperoni, white pie, hot honey chicken…",
    itemNoun: "pizza item",
  },
  "american-dragon": {
    slug: "american-dragon",
    name: "American Dragon",
    logo: "/images/logo-american-dragon.png",
    heroImage: "/images/portal-american-dragon.jpeg",
    accent: "#d13a2f",
    accentBright: "#ff6b55",
    accentDark: "#761c18",
    secondary: "#d6aa3a",
    eyebrow: "A Casper Group Brand · Chinese-American Wok Kitchen",
    format: "Wok · Wings · Noodles · Rice",
    heroLead: "Wok heat.",
    heroAccent: "American appetite.",
    heroTail: "The dragon stays hungry.",
    heroCopy: "Crispy classics, wok-fired steak and shrimp, lo mein, fried rice, wings, small plates, and family feasts with a bold modern identity.",
    orderCta: "Build a Dragon Order",
    serviceCta: "Plan a Dragon Feast",
    signatureEyebrow: "Dragon favorites",
    signatureHeading: "Familiar cravings. Serious wok energy.",
    standardEyebrow: "The wok standard",
    standardHeading: "High heat. Fast movement.",
    standardAccent: "Sauce with discipline.",
    standardCopy: "American Dragon is built around mise en place, wok temperature, batch control, sauce consistency, texture protection, and family-format service.",
    standards: ["Wok hot", "Batch small", "Sauce to order"],
    menuEyebrow: "The dragon menu",
    menuHeading: "Choose crispy, wok-fired, or full feast.",
    systemEyebrow: "The Dragon system",
    systemHeading: "Protein. Wok. Sauce. Fire.",
    systemCopy: "Choose the entrée or noodle, pick the protein, set the rice, control the heat, and scale the whole thing to a family feast.",
    systemSteps: [
      { title: "Choose the format", detail: "Wok entrée · Noodles · Rice · Wings" },
      { title: "Pick the protein", detail: "Chicken · Beef · Shrimp · Vegetable" },
      { title: "Set the sauce", detail: "Orange · Sesame · Mongolian · Chili garlic" },
      { title: "Feed the crew", detail: "Single bowl · Combo · Dragon Feast" },
    ],
    serviceEyebrow: "Feasts & event catering",
    serviceHeading: "Bring the dragon to the whole table.",
    serviceCopy: "Office lunches, family celebrations, production sets, festivals, private events, boxed meals, and large-format wok service.",
    serviceOptions: [
      { value: "family_feast", label: "Family feast" },
      { value: "boxed_meals", label: "Boxed meals" },
      { value: "event_catering", label: "Event catering" },
      { value: "mobile_wok", label: "Mobile wok service" },
    ],
    serviceTags: ["Family feast", "Boxed meals", "Buffet service", "Mobile wok"],
    clubName: "The Dragon List",
    clubHeading: "The first call goes to the hungry.",
    clubCopy: "Join for new wok drops, family specials, event windows, birthday offers, and first access to new locations.",
    favoriteLabel: "Favorite Dragon order",
    favoritePlaceholder: "General Dragon, lo mein, fire shrimp…",
    itemNoun: "wok item",
  },
};

export function getRemainingCasperBrand(slug: string) {
  return remainingCasperBrands[slug];
}
